name: Hello world

on:
   push:
    branches:
        -main
   pull_request:
    branches:
        -main
   workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            -users: actions/checkout@v2
            -name: helloworld
             run: echo 'hello world'
             shell: bash
    goodbye:
        runs-on: ubuntu-latest
        steps:
            -name: goodbye world
             run: echo 'goodbye'