name: Create a comment on new issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: 'dump github contest'
        run: echo '${{ toJSON(gihub.event)}}' | jq
        shell: bash
